fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
  forge_modules:
    mysql:
      repo: 'puppetlabs-mysql'
      ref: '3.11.0'
    apt:
      repo: 'puppetlabs-apt'
      ref: '2.4.0'
  symlinks:
    powerdns: "#{source_dir}"
