name: CI

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  test:
    name: "Static & Spec Tests (Ruby ${{ matrix.ruby }}, Puppet ${{ matrix.puppet }})"
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_WITH: "development"
    strategy:
      matrix:
        puppet: [7.0]
        ruby: [2.6, 2.7]
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      env:
        PUPPET_GEM_VERSION: ~> ${{ matrix.puppet }}
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
        rubygems: 3.2.3

    - name: Rubocop
      run: bundle exec rake rubocop

    - name: Test code
      run: bundle exec rake spec
