name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        puppet: [6.0.0, 7.0.0]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.60.1
      with:
        ruby-version: 2.6.10
    - name: Test code
      env:
        PUPPET_VERSION: ~> ${{ matrix.puppet }}
      run: |
        bundle install --path vendor/bundle --without development
        bundle exec rake test
